FROM python:3.10.20-slim AS builder

WORKDIR /app
COPY requirements.txt ./
RUN pip install --prefix=/install -r requirements.txt
COPY app.py ./

FROM python:3.10.20-slim

WORKDIR /app
COPY --from=builder /install /usr/local
COPY --from=builder /app/app.py ./

EXPOSE 5000
CMD ["python", "app.py"]
